u-projects/university-projects/Servicios Web/Taller5/Taller5/blog/config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  get 'posts/bienvenido' => 'posts#bienvenido'
  
  resources :tests

  resources :posts do
    resources :comments
  end

end

u-projects/university-projects/Servicios Web/Taller5/Taller5/blog/app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :post
end

u-projects/university-projects/Servicios Web/Taller5/Taller5/blog/app/models/post.rb
class Post < ActiveRecord::Base
	has_many :comments
	validates :tittle, :body, presence: true, length: {minimum: 2}
end

u-projects/university-projects/Servicios Web/Taller5/Taller5/blog/app/models/test.rb
class Test < ActiveRecord::Base
end

u-projects/university-projects/Servicios Web/Taller5/Taller5/blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

u-projects/university-projects/Servicios Web/Taller5/Taller5/blog/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    #@comment = Comment.new(comment_params)
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @post, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:post_id, :body)
    end
end

u-projects/university-projects/Servicios Web/Taller5/Taller5/blog/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  def bienvenido
    @var = "Halp!!"
  end
  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:tittle, :body)
    end
end

u-projects/university-projects/Servicios Web/Taller5/Taller5/blog/app/controllers/tests_controller.rb
class TestsController < ApplicationController
  before_action :set_test, only: [:show, :edit, :update, :destroy]

  # GET /tests
  # GET /tests.json
  def index
    @tests = Test.all
  end

  # GET /tests/1
  # GET /tests/1.json
  def show
  end

  # GET /tests/new
  def new
    @test = Test.new
  end

  # GET /tests/1/edit
  def edit
  end

  # POST /tests
  # POST /tests.json
  def create
    @test = Test.new(test_params)

    respond_to do |format|
      if @test.save
        format.html { redirect_to @test, notice: 'Test was successfully created.' }
        format.json { render :show, status: :created, location: @test }
      else
        format.html { render :new }
        format.json { render json: @test.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tests/1
  # PATCH/PUT /tests/1.json
  def update
    respond_to do |format|
      if @test.update(test_params)
        format.html { redirect_to @test, notice: 'Test was successfully updated.' }
        format.json { render :show, status: :ok, location: @test }
      else
        format.html { render :edit }
        format.json { render json: @test.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tests/1
  # DELETE /tests/1.json
  def destroy
    @test.destroy
    respond_to do |format|
      format.html { redirect_to tests_url, notice: 'Test was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_test
      @test = Test.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def test_params
      params.require(:test).permit(:nombre, :apellido)
    end
end

u-projects/university-projects/Servicios Web/Taller5/Taller5/blog/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	@name = "Carlos Motta"
  	@limit = 3
  end
end

u-projects/university-projects/Servicios Web/Taller5/Taller5/blog/app/helpers/application_helper.rb
module ApplicationHelper
end

u-projects/university-projects/Servicios Web/Taller5/Taller5/blog/app/helpers/comments_helper.rb
module CommentsHelper
end

u-projects/university-projects/Servicios Web/Taller5/Taller5/blog/app/helpers/posts_helper.rb
module PostsHelper
end

u-projects/university-projects/Servicios Web/Taller5/Taller5/blog/app/helpers/tests_helper.rb
module TestsHelper
end

u-projects/university-projects/Servicios Web/Taller5/Taller5/blog/app/helpers/welcome_helper.rb
module WelcomeHelper
end

u-projects/university-projects/Servicios Web/Taller5/Taller5/blog/app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :post_id %><br>
    <%= f.text_field :post_id %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_field :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

u-projects/university-projects/Servicios Web/Taller5/Taller5/blog/app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

u-projects/university-projects/Servicios Web/Taller5/Taller5/blog/app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <thead>
    <tr>
      <th>Post</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.post_id %></td>
        <td><%= comment.body %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

u-projects/university-projects/Servicios Web/Taller5/Taller5/blog/app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

u-projects/university-projects/Servicios Web/Taller5/Taller5/blog/app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Post:</strong>
  <%= @comment.post_id %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

u-projects/university-projects/Servicios Web/Taller5/Taller5/blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'default', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

u-projects/university-projects/Servicios Web/Taller5/Taller5/blog/app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :tittle %><br>
    <%= f.text_field :tittle %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

u-projects/university-projects/Servicios Web/Taller5/Taller5/blog/app/views/posts/bienvenido.html.erb
<h1><%=@var %></h1>
<p>My var halp mudafuca</p>

u-projects/university-projects/Servicios Web/Taller5/Taller5/blog/app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

u-projects/university-projects/Servicios Web/Taller5/Taller5/blog/app/views/posts/index.html.erb
<h1>Listing posts</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Tittle</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.id %></td>
        <td><%= post.tittle %></td>
        <td><%= post.body %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

u-projects/university-projects/Servicios Web/Taller5/Taller5/blog/app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

u-projects/university-projects/Servicios Web/Taller5/Taller5/blog/app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tittle:</strong>
  <%= @post.tittle %>
</p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<h2>Comments</h2>
<div id="comments">
	<!-- Se ajusta para que traiga los posts -->
	<% @post.comments.each do |comment| %>
		<%=div_for comment do %>
			<p>
				<strong> Posted
					<%=time_ago_in_words(comment.created_at) %>
				</strong><br/>
				<%=h(comment.body) %>
			</p>
		<% end %>
	<% end %>
</div>

<%= form_for([@post, Comment.new]) do |f| %>
	<div class="field">
		<p><%= f.label :body, "New Comment" %><br/>
		   <%= f.text_area :body %>
		</p>
	</div>
	<div class="actions">
			<p><%= f.submit "Add comment" %>
			</p>
	</div>
<% end %>



<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

u-projects/university-projects/Servicios Web/Taller5/Taller5/blog/app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Primera vista desarrollada en servicios web</p>
<p>Find me in app/views/welcome/index.html.erb</p>
<p><%=@name %></p>
<% @limit.times do %>
	<p>Imprimiento un ciclo modafuca</p>
<% end %>